package interactions;

/**
 * ...
 * @author Chris Porter
 */
enum HandPointerState
{

	NUI_HANDPOINTER_STATE_NOT_TRACKED;
	NUI_HANDPOINTER_STATE_TRACKED;
	NUI_HANDPOINTER_STATE_ACTIVE;
	NUI_HANDPOINTER_STATE_INTERACTIVE;
	NUI_HANDPOINTER_STATE_PRESSED;
	NUI_HANDPOINTER_STATE_PRIMARY_FOR_USER;
	
}