package ;

/**
 * ...
 * @author Chris Porter
 */
enum ImageResolution
{
	NUI_IMAGE_RESOLUTION_INVALID;
    NUI_IMAGE_RESOLUTION_80x60;
    NUI_IMAGE_RESOLUTION_320x240;
    NUI_IMAGE_RESOLUTION_640x480;
    NUI_IMAGE_RESOLUTION_1280x960;
}