package ;

/**
 * ...
 * @author Chris Porter
 */
enum SkeletonPositionIndex
{
	NUI_SKELETON_POSITION_HIP_CENTER;
    NUI_SKELETON_POSITION_SPINE;
    NUI_SKELETON_POSITION_SHOULDER_CENTER;
    NUI_SKELETON_POSITION_HEAD;
    NUI_SKELETON_POSITION_SHOULDER_LEFT;
    NUI_SKELETON_POSITION_ELBOW_LEFT;
    NUI_SKELETON_POSITION_WRIST_LEFT;
    NUI_SKELETON_POSITION_HAND_LEFT;
    NUI_SKELETON_POSITION_SHOULDER_RIGHT;
    NUI_SKELETON_POSITION_ELBOW_RIGHT;
    NUI_SKELETON_POSITION_WRIST_RIGHT;
    NUI_SKELETON_POSITION_HAND_RIGHT;
    NUI_SKELETON_POSITION_HIP_LEFT;
    NUI_SKELETON_POSITION_KNEE_LEFT;
    NUI_SKELETON_POSITION_ANKLE_LEFT;
    NUI_SKELETON_POSITION_FOOT_LEFT;
    NUI_SKELETON_POSITION_HIP_RIGHT;
    NUI_SKELETON_POSITION_KNEE_RIGHT;
    NUI_SKELETON_POSITION_ANKLE_RIGHT;
    NUI_SKELETON_POSITION_FOOT_RIGHT;
    NUI_SKELETON_POSITION_COUNT;
}